#######################################
# Device specific Config Begins Below #
#######################################

binary_sensor:
  # the 7 lines below define the reset button (button on the sonoff mini device)
  - platform: gpio
    pin: GPIO00
    id: reset
    internal: true # hides reset switch from HomeAssistant
    filters:
      - invert:
      - delayed_off: 10ms
    # the 3 lines below toggle the main relay on press of reset button
    on_press:
      - light.toggle:
          id: light_id

  # the lines below toggle the main relay on command with the S1/S2 lines
  # to toggle the light with a push button the on_release must not be present (only on press must toggle the light)
  # to toggle the light with a traditional (circuit open/close) switch on_press and on_release must toggle the light
  - platform: gpio
    name: relay_toggle
    internal: true # hides relay toggle from HomeAssistant
    pin: GPIO04
    id: gpio_light_id
    filters:
      - delayed_off: 10ms
    on_press:
      then:
        - light.toggle:
            id: light_id

  # the 2 lines below create a status entity in HomeAssistant.
  - platform: status
    name: ${device_name} Status

status_led:
  pin:
    number: GPIO13

output:
  # the 3 lines below control the main relay
  - platform: gpio
    pin: GPIO12
    id: main_light_relay
  # the 3 lines below control the Blue LED
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: True

light:
  # the 4 lines below define the main relay as a light
  - platform: binary
    name: ${device_name} # you can enter a custom name to appear in HomeAsistant here.
    output: main_light_relay
    id: light_id
  # the 4 lines below define the Blue LED light on Sonoff Mini, to expose in HomeAssistant remove line "internal: true"
  - platform: monochromatic
    name: ${device_name}_blueled
    output: blue_led
    internal: true # hides the Blue LED from Homeassistant
